_target_: model.modules.PIPPack
node_features: 128
edge_features: 128
hidden_dim: 128
num_mpnn_layers: 3
k_neighbors: 30 
augment_eps: 0. 
use_ipmp: False 
use_ipmp_ipa: False
n_points: null
dropout: 0.1
act: relu
predict_bin_chi: True
n_chi_bins: 72
predict_offset: True
position_scale: 1.0
loss:
  chi_nll_loss_weight: 1.0
  chi_mse_loss_weight: 1.0
  offset_mse_loss_weight: 1.0
