# Default configuration for inference.

defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

inference:
  # Inference arguments
  weights_path: /proj/kuhl_lab/users/nzrandol/PIPPack/model_weights/
  model_name: pippack_model_1
  pdb_path: ???
  output_dir: pippack_output
  n_recycle: 3
  temperature: 0.0
  replace_seqs: False
  use_resample: False
  force_cpu: False
  batch_size: 10000
  seed: 42

  # Debugging
  debug: False

  resample_args:
    sample_temp: 0.5
    clash_overlap_tolerance: 0.6
    pro_tolerance_factor: 12
    max_iters: 10
    metropolis_temp: 0.000005

hydra:
  run:
    dir: .
  output_subdir: null