# Default configuration for ensembled inference.

defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

inference:
  # Inference arguments
  weights_path: /proj/kuhl_lab/users/nzrandol/PIPPack/model_weights/
  model_names:
    - pippack_model_1
    - pippack_model_2
    - pippack_model_3
  pdb_path: ???
  output_dir: pippack_ensemble_output
  n_recycle: 3
  temperature: 0.0
  replace_seqs: False
  force_cpu: False
  batch_size: 10000
  seed: 42

  # Debugging
  debug: False

hydra:
  run:
    dir: .
  output_subdir: null