_target_: data.top2018_dataset.Top2018DataModule
data_dir: "~/kuhl_lab/users/nzrandol/protein-datasets/"
removal_list_file: "~/kuhl_lab/users/nzrandol/protein-datasets/casp/top2018_mc_v2.01_overlap.txt"
filter_level: "mc"
version: "2.01"
seq_id: "40pc"
n_chi_bins: 72
crop_size: null
batch_size: 15
num_workers: 0
num_chains: -1